//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coberturas
    {
        public Coberturas()
        {
            this.PlanCobertura = new HashSet<PlanCobertura>();
        }
    
        public int IdCobertura { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual ICollection<PlanCobertura> PlanCobertura { get; set; }
    }
}
